drop table if exists bookmarks;

create table bookmarks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    book text not null
);

--insert test data
insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 8', 'Book 2');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 9', 'Book 2');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 3', 'Book 2');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 1', 'Book 12');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 2', 'Book 10');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 1', 'Book 4');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 8', 'Book 11');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 2', 'Book 12');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 28', 'Book 1');

insert into bookmarks 
  ( title, book ) 
  values ('Bookmark 20', 'Book 2');